package com.devMohanned.devteam.wallpaper_app.OnePiece;


public class Utilities {
    public static String app_id_num = "ca-app-pub-4918992534065924~8241388345";
    public static String Interstitial_id = "ca-app-pub-4918992534065924/3535856579";
    public static String banner_id = "ca-app-pub-4918992534065924/2605918282";

    public static int IMAGES[] = {
            R.drawable.one_piece_27,
            R.drawable.one_piece_33,
            R.drawable.one_piece_32,
            R.drawable.one_piece_18,
            R.drawable.one_piece_37,
            R.drawable.one_piece_19,
            R.drawable.one_piece_20,
            R.drawable.one_piece_21,
            R.drawable.one_piece_22,
            // R.drawable.one_piece_23,
            R.drawable.one_piece_24,
            R.drawable.one_piece_25,
            R.drawable.one_piece_26,

            R.drawable.one_piece_28,
            R.drawable.one_piece_29,

            R.drawable.one_piece_31,

            R.drawable.one_piece_34,
            //R.drawable.one_piece_35,
            R.drawable.one_piece_36,

            R.drawable.one_piece_38,
            R.drawable.one_piece_39,
            R.drawable.one_piece_40,
            R.drawable.one_piece_41,
            R.drawable.one_piece_42,
            R.drawable.one_piece_43,
            //R.drawable.one_piece_44,
            R.drawable.one_piece_45,
            R.drawable.one_piece_46,
            R.drawable.one_piece_47,
            R.drawable.one_piece_48,
            R.drawable.one_piece_49,
            R.drawable.one_piece_50,
            R.drawable.one_piece_51,
            R.drawable.one_piece_52,
            R.drawable.one_piece_53,
            R.drawable.one_piece_54,
            R.drawable.one_piece_55,
            //R.drawable.one_piece_56,
            R.drawable.one_piece_57,
            R.drawable.one_piece_58,
            R.drawable.one_piece_59,
            // R.drawable.one_piece_60,
            R.drawable.one_piece_61,
            R.drawable.one_piece_62,
            R.drawable.one_piece_63,
            R.drawable.one_piece_64,
            R.drawable.one_piece_65,
            R.drawable.one_piece_66,
            R.drawable.one_piece_67,
            R.drawable.one_piece_68,
            R.drawable.one_piece_69,
            R.drawable.one_piece_70,
            R.drawable.one_piece_1,
            R.drawable.one_piece_2,
            R.drawable.one_piece_3,
            R.drawable.one_piece_4,
            //R.drawable.one_piece_5,
            R.drawable.one_piece_6,
            R.drawable.one_piece_7,
            R.drawable.one_piece_8,
            R.drawable.one_piece_9,
            R.drawable.one_piece_10,
            //R.drawable.one_piece_11,
            R.drawable.one_piece_12,
            R.drawable.one_piece_13,
            //R.drawable.one_piece_14,
            //R.drawable.one_piece_15,
            R.drawable.one_piece_16,
            R.drawable.one_piece_17,
            R.drawable.one_piece_30,

    };
}
